name: Automation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: GitHub Actions
    strategy:
      matrix:
        operating-system: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Cached Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Install dependencies if git hash has changed
      - name: Install Maven Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bash ./mvnw -f .dependencies/dependencies.pom.xml -U compile
      - name: Run KtLint
        run: bash ./gradlew clean ktlintCheck --refresh-dependencies
      - name: Run Test Suite
        run: bash ./gradlew clean build test --refresh-dependencies
