name: CI Automation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GRADLE_OPTS: -Dorg.gradle.caching=true
jobs:
  lint:
    name: Perform ktlint analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ktlint
        run: java -jar assets/ktlint.jar
  test:
    name: Test Suite
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - name: Log and prepare environment information
        run: java -version
      - name: Fetch Gradle dependencies
        run: bash ./gradlew clean --refresh-dependencies
      - name: Build project from source
        run: bash ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: main-project-build
          path: build/
      - name: Execute Kotlin tests
        run: bash ./gradlew test
  samples:
    needs: [test]
    name: Ensure sample projects run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build parent project
        run: bash ./gradlew build --refresh-dependencies
      - name: FactorialJIT Example
        run: bash samples/run.sh factorial-jit