name: All llvm4kt Test Suites
on: [push]
jobs:
  run:
    name: Execute Test Suite
    strategy:
      matrix:
        architecture: [x64, x86]
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Install LLVM
        run: |
          gradle clean build --refresh-dependencies
      - name: Run tests
        run: |
          gradle clean test